### ISSUE TITLE
https://dash.soketi.app/register seems to be down

### ISSUE THREAD

**Issue by leoboom-isme** [soketi/pws#1082]
https://dash.soketi.app/register is down again.

**Comment by vesper8** [comment]
So to be clear.. we can't use Soketi Serverless until the dash comes back up ?

**Comment by Wundero** [comment]
> So to be clear.. we can't use Soketi Serverless until the dash comes back up ?

I believe the cloudflare workers should still be alive if you have already configured them - those should be separate to Soketi's infra. However, you cannot create or configure any new soketi serverless projects while they are down. Quite frustrating how often the dashboard goes down.

**Comment by vesper8** [comment]
Can you help me understand what the dashboard offers that cannot be self-hosted? Shouldn't this work without any intervention from Soketi? I guess I don't understand what Soketi is adding beyond instructions.

**Comment by Wundero** [comment]
> Can you help me understand what the dashboard offers that cannot be self-hosted? Shouldn't this work without any intervention from Soketi? I guess I don't understand what Soketi is adding beyond instructions.

I will note that I am not a contributor of soketi nor am I affiliated in any way, so this may be incorrect information, but this is what I understand from having used the serverless stuff so far.

The code of their serverless build is closed source, so "self-hosting" it isn't particularly feasible, since we can't deploy the source to cloudflare workers manually. What the dashboard does is allow you to initialize your setup by installing their serverless implementation onto your own cloudflare workers. The dashboard handles configuration as well, such as max connections, rate limits, environments, etc. that you may want to change. However, once you are done configuring the software and it is deployed to cloudflare, it never interacts with the dashboard, and neither does the software you write which interfaces with the cloudflare worker. This means that the reliability of your websockets is not really dependent on the soketi dashboard being alive to function, but meta services like updates and configuration cannot be made while the dashboard is down, nor can new projects be created.

The serverless implementation doesn't cost any money besides what you pay for cloudflare's workers, so I wouldn't really describe these things as "value adds" necessarily, but Soketi offers more than just instructions if you use the serverless (since they do the setup for you). You can setf-host the normal Soketi implementation, and to great effect, by orchestrating soketi containers and a backend communication framework (e.g. redis clusters), however there is added cost to you in the time you must spend doing that setup and maintenance yourself.

**Comment by vesper8** [comment]
@Wundero Thank you for that detailed explanation! Looks very much accurate!

Let's hope the dashboard comes back up.. or else let's hope they open-source the bits that make all of this work so we can configure the workers ourselves!

**Comment by rennokki** [comment]
Soketi on Cloudflare Workers was a good test for infrastructure at Edge. It was enough to run for most people who got small loads — testing locally, small internal projects, or up to a few tens of concurrent connections. I've seen some people even reached hundreds and thousands of concurrent connections thanks to the Hibernation API, which allowed up to 32,000 connections at once.

I've decided to put the Cloudflare Workers version on pause for now, and focus on the main stage — [going Interstellar](https://interstellar.soketi.app).

If you still consider the Cloudflare Workers version to be useful for your use case, please contact me (<alex@thecodefather.co>) and explain further the use case and I will consider looking forward to it.
