### ISSUE TITLE
the Soketi project is abandoned

### ISSUE THREAD

**Issue by tarreislam** [soketi/pws#1114]
Since this project obviously has been abandoned, I would suggest you guys look out for "Laravel Reverb", which will probably launch any time soon

It is an official release from laravel built using the Pusher protocol, meaning you can use it with any pusher client on any programming language, or even port the reverb functionality from Reverb to roll your own pusher service.

https://reverb.laravel.com/
https://www.youtube.com/watch?v=TkYXIHgdrgA

**Comment by chrispage1** [comment]
👍🏻 I have been keeping my eye on reverb and looking forward to the release. I'll imagine it'll likely take over our Soketi cluster as I know it'll have good support from core Laravel team

**Comment by unleashit** [comment]
Just wondering if you've seen an official statement that it's been abandoned? Looks like commits have been made as recently as 5 days ago, but I do notice the included uWebSockets hasn't been updated in ages and won't even support Node 20 lts...

**Comment by chrispage1** [comment]
@unleashit - no official confirmation on it being abandoned, @rennokki would have to tell us that. The latest change was an update to the README after no commits for four months since October and a number of outstanding PR's and issues.

Fingers crossed it's not, but I think it is 👎

**Comment by unleashit** [comment]
Could just be taking a break, but yeah that's a long time. Bummer because Soketi almost had me convinced to rewrite my open source help desk to work with the Pusher SDK. Seemed great for a websockets libary. If users like cloud services they can use Pusher, if not spin up a Soketi container.

**Comment by rennokki** [comment]
No, it is not abandoned. Just put on pause. Soketi is supposed to be unopinionated, without relying on specific frameworks.

**Comment by tarreislam** [comment]
> No, it is not abandoned. Just put on pause. Soketi is supposed to be unopinionated, without relying on specific frameworks.

Okay, but its getting less and less viable in production due to not being maintained, there fore I posted this issue.

**Comment by alexhackney** [comment]
@tarreislam I have this running in production and its fine. We use a reverse proxy infront of it to handle the ssl but I've had thousands of simultaneous connections on it, without any issues.

I'm not sure what more you want from him at this point.

**Comment by tarreislam** [comment]
> @tarreislam I have this running in production and its fine. We use a reverse proxy infront of it to handle the ssl but I've had thousands of simultaneous connections on it, without any issues.
> 
> I'm not sure what more you want from him at this point.

I am happy its working for your needs.

**Comment by unleashit** [comment]
> I'm not sure what more you want from him at this point.

For me, I would never choose to use a tool that didn't have a reasonably good outlook for at least security updates and bug fixes. Anecdotally, I have some old Joomla sites that were hacked over and over to the point that I could not host them on several different VPS providers due to their locking my accounts. Yet I can't blame Joomla for not maintaining that old code forever. 

Personally, I don't think anyone doing open source owes anything to anyone. If "I" was maintaining a popular package, sure I would at least try to update the users if I were planning to quit or go on a long Sabbatical. But people are human... can't always predict the future... and that's a totally fine trade off IMO. It's much worse when a corporation ends an offering, many times giving you until the end of the month to do your scrambling.
